# This is a basic workflow that is manually triggered
name: Update Database

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "src/**/*.ts"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Installing Yarn
      run: npm install -g yarn
    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
    - name: Installing dependencies
      run: yarn
    - name: Run Script
      run: yarn start
    - name: Add & Commit
      uses: EndBug/add-and-commit@v5.2.0
      with:
        add: .
        author_name: Alex4386
        author_email: psh010209@gmail.com
        # The message for the commit
        message: "chore: update database"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
